---
- name: Unzip Harbor sources
  unarchive:
    src: "{{ harbor_release_url }}"
    dest: "{{ harbor_install_path }}/"
    remote_src: yes

- name: harbor.yml configuration
  template:
    src: harbor.yml.j2
    dest: "{{harbor_install_path}}/harbor/harbor.yml"

- name: If add_trivy=false, execute install.sh
  shell: "{{harbor_install_path}}/harbor/install.sh"
  args:
    chdir: "{{harbor_install_path}}/harbor/"
  when: not add_trivy

- name: If add_trivy=true, execute install.sh --with-trivy
  shell: "{{harbor_install_path}}/harbor/install.sh --with-trivy"
  args:
    chdir: "{{harbor_install_path}}/harbor/"
  when: add_trivy
