---
- name: "Playbook to install Harbor"
  hosts: localhost
  vars_prompt:
    - name: db_password
      prompt: Harbor internal database password
      default: Harbor123456
    - name: harbor_admin_password
      prompt: Harbor web ui password
      default: Harbor123456
  vars:
    harbor_hostname: localhost
    add_trivy: true
    use_https : true
    generate_ssl: true
    harbor_install_path : /usr/local/
    harbor_online_installer_version: 2.8.2
  
  roles:
     - prereqs_harbor
     - install_harbor
