---
- name: Create necessary directory if generate_ssl=true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/cert/
    - /data/internal_cert/
    - /etc/docker/certs.d/{{ harbor_hostname| default(ansible_fqdn) }}/
  when: generate_ssl

- name: Generate CA if generate_ssl=true
  shell: openssl req -newkey rsa:4096 -nodes \
          -sha512 -keyout /data/cert/ca.key -x509 \
          -days 365 -out /data/cert/ca.crt \
          -subj "/C=FR/ST=Herault/L=Montpellier/O={{ ansible_domain| default("Groupe Isia") }}/CN={{ ansible_domain| default("dummy") }}"
  when: generate_ssl

- name: Generate CSR from CA if generate_ssl=true
  shell: openssl req -newkey rsa:4096 -nodes -sha512 \
          -keyout /data/cert/{{ harbor_hostname| default(ansible_fqdn) }}.key \
          -out /data/cert/{{ harbor_hostname| default(ansible_fqdn) }}.csr \
          -subj "/C=FR/ST=Herault/L=Montpellier/O={{ ansible_domain| default("Groupe Isia") }}/CN={{ harbor_hostname| default(ansible_fqdn) }}"
  when: generate_ssl

- name: Create x509 v3 extension file
  template:
    src: v3.ext.j2
    dest: /data/cert/v3.ext
  when: generate_ssl

- name: Generate self signed certificate from CSR if generate_ssl=true
  shell: openssl x509 -req -days 365 -in /data/cert/{{ harbor_hostname| default(ansible_fqdn) }}.csr \
          -extfile /data/cert/v3.ext \
          -CA /data/cert/ca.crt -CAkey /data/cert/ca.key \
          -CAcreateserial -out /data/cert/{{ harbor_hostname| default(ansible_fqdn) }}.crt 
  when: generate_ssl

- name: Add ca.crt in autorised Docker CA if generate_ssl=true
  copy: 
    src: /data/cert/ca.crt
    dest: /etc/docker/certs.d/{{ harbor_hostname| default(ansible_fqdn) }}/ca.crt
    remote_src: yes
  when: generate_ssl

- name: Generate CA for internal use if generate_ssl=true
  shell: openssl req -newkey rsa:4096 -nodes \
          -sha512 -keyout /data/internal_cert/harbor_internal_ca.key -x509 \
          -days 365 -out /data/internal_cert/harbor_internal_ca.crt \
          -subj "/C=FR/ST=Herault/L=Montpellier/O={{ ansible_domain| default("Groupe Isia") }}/CN={{ ansible_domain| default("dummy") }}"
  when: generate_ssl

- name: Generate SSL certificates for internal use if generate_ssl=true
  shell: docker run -v /:/hostfs goharbor/prepare:v2.8.2 gencert -p /data/internal_cert
  when: generate_ssl